@startuml
left to right direction
actor BankSystem
actor Customer

actor Technician


rectangle "ATM System" as ATM {
    Customer --> (Withdraw Cash)
    Customer --> (Deposit Funds)
    Customer --> (Transfer Funds)
    Customer --> (Check Balance)
    Technician --> (Perform Maintenance)
    Technician --> (Restock Cash)
    BankSystem --> (Validate Account Status)
    BankSystem --> (Verify Account Balance)


    (Withdraw Cash) ..> (Validate Account Status) : <<include>>
    (Deposit Funds) ..> (Validate Account Status) : <<include>>
    (Transfer Funds) ..> (Validate Account Status) : <<include>>
    (Check Balance) ..> (Verify Account Balance) : <<include>>
    (Perform Maintenance) ..> (Suspend Customer Interaction) : <<include>>
    (Restock Cash) ..> (Suspend Customer Interaction) : <<include>>
}

@enduml
