@startuml
left to right direction
skinparam backgroundColor white


:Administrator: --left->(List Accounts)
:Administrator: -->(Create Account)
:Administrator: -down->(Delete Venue)
:Administrator: --->(View Account)
:Administrator: -up->(Delete Account)
:Administrator: -right->(Delete Event)
:Administrator: --->(View Venue)
:Administrator: -->(Update Account)
:Administrator: --->(List Events)
:Administrator: --->(List Venues)
:Administrator:--->(View Event)

:User:--->(View Account)
:User:--->(Register Account)
:User:--->(List Venues)
:User:--->(View Venue)
:User:--->(List Events)
:User:--->(Update Profile)
:User:--->(View Event)
:User:--left-->(Buy Ticket)
:User:--right-->(View Ticket)
:User:-up->(List Tickets)
:Organiser:

(Add Venue) <-up- :Organiser:
(Update Venue) <- :Organiser:
(Create Event) <-left-:Organiser:
(View Event) <--- :Organiser:
(List My Events) <-- :Organiser:
(List My Venues) <-- :Organiser:
(View Account) <--- :Organiser:
(View Venue) <--- :Organiser:
(Update Profile) <--- :Organiser:

@enduml

