@startuml
left to right direction

:Administrator: -up->(Remove Account)
:Administrator: -->(Update Account)
:Administrator: -left->(List Accounts)
:Administrator: -->(Create Account)
:Administrator: -->(Remove Venues)

:User:--->(Create Account)
:User:--->(Update Account)
:User:--->(View Account)
:User:--->(Register Account)
:User:--->(List Venues)
:User:--->(View Venue)
:User:--->(List Events)
:User:--->(View Event)
:User:--left-->(Buy Tickets)
:User:--right-->(View Tickets)

:Organiser:

(Add Venue) <-up- :Organiser:
(Edit Venue) <- :Organiser:
(Create Event) <-left-:Organiser:
(View Event) <--- :Organiser:
(List Events) <--- :Organiser:
(List Venues) <--- :Organiser:
(Register Account) <--- :Organiser:
(View Account) <--- :Organiser:
(View Venue) <--- :Organiser:
(Update Account) <--- :Organiser:

@enduml
