@startuml
left to right direction
skinparam monochrome true
skinparam backgroundColor white
skinparam shadowing false
skinparam linetype ortho
skinparam lineThickness 3   ' Thickness of line
skinparam noteMargin 30     ' Margins for comments
skinparam ranksep 100        ' Control vertical spacing
skinparam nodesep 200        ' Control horizontal spacing
skinparam classFontSize 12
skinparam ArrowFontSize 12
skinparam classBorderThickness 1
skinparam classAttributeIconSize 0

hide class circle
hide empty members
hide stereotypes

skinparam class {
    BorderColor black
    ArrowColor black
    FontColor black
    FontName Arial
    FontSize 12
}



' Account Management Group
package "Account Management" {
class ROLE {
        +ADMINISTRATOR
        +ORGANISER
        +CUSTOMER
    }
    class Account {
        - name: String
        - email: String
        - password: String
        - role: ROLE
        +getName(): String
        +getEmail(): String
        +getPassword(): String
        +setName(name: String)
        +setEmail(email: String)
        +setPassword(password: String)
    }
    class Administrator {
    _Administrator(name: String,email:String,password:String)_
    }
    class Organiser {
        - address: String
        - companyName: String
        - phoneNumber: String
        _Organiser(name: String,email:String,password:String,address: String,companyName: String,phoneNumber: String)_
        +getAddress():String
        +getCompanyName():String
        +getPhoneNumber(): String
        +setAddress(address: String)
        +setCompanyName(companyName: String)
        +setPhoneNumber(phoneNumber: String)
    }
    class Customer {
    _Customer(name: String,email:String,password:String)_
    getTickets():List<Ticket>
    }

    class AccountService {
        +createAdminAccount(name: String,email: String,password:String): Boolean
        +createCustomerAccount(name: String,email: String,password:String): Boolean
        +createOrganiserAccount(name: String,email: String,password:String): Boolean
        +registerAccount(name: String,email: String,password:String): Boolean
        +getAccount(email: String): Account
        +getCustomer(customerEmail:String):Customer
        +getOrganiser(organiserEmail:String):Organiser
        +getAccounts():Account[*]
        +deleteAccount(accountEmail: String): Boolean
        +updateAccount(account: Account): Boolean
        +checkAccountExist(accountEmail:String):Boolean
    }


    Administrator --|> Account
    Organiser --|> Account
    Customer --|> Account
    AccountService "1"--> "-accounts * "Account
}

' Venue Management Group
package "Venue Management" {
    class Venue {
        - name: String
        - address: String
        - contactName: String
        - contactPhoneNumber: String
        - contactEmail: String
        - capacity: TicketAvailability[*]
        _Venue(name: String,address: String,contactName: String,contactPhoneNumber: String,contactEmail: String,capacity: TicketAvailability[*])_
        +getName():String
        +getAddress():String
        +getContactName():String
        +getContactPhoneNumber():String
        +getContactEmail():String
        +getTicketAvailabilities():TicketAvailability[*]
        +setName(name: String)
        +setAddress(address: String)
        +setContactName(contactName: String)
        +setContactPhoneNumber(contactPhoneNumber: String)
        +setContactEmail(contactEmail: String)
        +setTicketAvailabilities(ticketAvailabilities:TicketAvailability[*])
    }

    class VenueService {
        +getVenue(venueName: String):Venue
        +getVenues():Venue[*]
        +createVenue(name: String,address: String,contactName: String,contactPhoneNumber: String,contactEmail: String,capacity: TicketAvailability[*]): Boolean
        +readVenue(name: String): VenueDetails
        +updateVenue(name: String, venueDetails: VenueDetails): Boolean
        +deleteVenue(name: String): Boolean
        +getVenue(name: String): Venue
        +getVenueName(name: String):String
        +getVenueCapacity(name: String): int
        +saveVenue(name: String):Boolean
        +checkDuplicateVenue(venue: Venue)
        +selectVenue(name: String)
        +checkVenueUsage(name: String)
    }



    VenueService "1"--> "-venues * "Venue
}

' Event Management Group
package "Event Management" {
    class Event {
        - name: String
        - description: String
        - date: Date
        - time: Time
         _Event(name: String, description: String, date: Date, time: Time,venue: Venue,ticketQuantities: TicketQuantities)_
        +getName(): String
        +getDescription():String
        +getDate():Date
        +getTime():Time
        +setName(name: String)
        +setDescription(description: String)
        +setDate(date: Date)
        +setTime(time: Time)
    }

    class EventService {
        +createEvent(name: String, description: String, date: Date, time: Time,venue: Venue,ticketQuantities: TicketQuantities): Boolean
        +deleteEvent(name: String): Boolean
        +updateEvent(name: String, description: String, date: Date, time: Time,venue: Venue,ticketQuantities: TicketQuantities): Boolean
        +getEvent(name: String):Event
        +getEvents():List<Event>
        +saveEvent(event: Event):Boolean
        +getVenueUsage(venueName: String): List<Event>
        +getAvailableVenues(date: Date,time: Time):List<Venue>
    }



    Venue "1 -venue" <--"1" Event
    EventService "1"--> "-events *" Event
}

' Ticket Management Group
package "Ticket Management" {
    class Ticket {
            ' Ticket class with no attributes, representing a relationship
            - type : String
            - price : Double

        }

    class TicketQuantities {
            - numberSold: int
            - price: double
            _TicketQuantities(ticketTypeName,numberAvailable,price)_
            +getNumberRemain():int
            +getNumberSold():int
            +getPrice():double
            +setNumberRemain(numberRemain: int)
            +setNumberSold(numberSold: int)
            +setPrice(price: double)
        }
     class TicketAvailability {
                - ticketTypeName: String
                - numberAvailable: int
                _TicketAvailability(ticketTypeName,numberAvailable)_
                +getTicketTypeName():String
                +getNumberAvailable():int
                +setTicketTypeName(ticketTypeName: String)
                +setNumberAvailable(number: int)

            }

    class TicketService {
        +getTicket(userEmail: String, eventName: String): TicketDetails
        +buyTicket(userEmail: String, eventName: String, ticketType: String): TicketDetails
        +getCustomerRegistrations(eventName: event):List<Customer>
        +getTicketOwner(eventName: String):Customer
        +getTicketEvent(userEmail: String):Event
        +getTicketInfo(eventName: String,userEmail: String):TicketQuantities

    }




    Venue "1 -venue" --> "-ticketAvailabilities*" TicketAvailability : creates
    TicketAvailability --|> TicketQuantities
    Event "1"--> "1 -TicketQuantities" TicketQuantities: determines price
    Customer "1"--> "-tickets 0..* " Ticket : purchases
    Ticket "1"--> "-event 1" Event : related to
    Ticket "1"--> "1 -ticketQuantities" TicketQuantities : get Info
    TicketService "1"-->"-tickets *" Ticket
}

' System classes for each module
class AccountSystem {
    +login(email: String, password: String): Boolean
    +logout(): void
    +createAccount(accountDetails): Boolean
    +deleteAccount(accountEmail: String): Boolean
    +viewAccount(accountEmail: String): AccountDetails
    +updateAdministratorAccount(newName: String, newPassword:String,newEmail:String)
    +updateCustomerAccount(newName: String, newPassword:String,newEmail:String)
    +updateOrganizerAccount(newName: String, newPassword:String,newEmail:String,newAddress:String,newCompanyName :String, newPhoneNumber:String)
    +displayEditAccountPage(selectedAccount)
    +displayAccounts(accounts:Account[*])
    +disableAccount(accountEmail:String):Boolean
    +selectAccount(accountEmail:String)
    +displayEditAccountPage(accountEmail: String)
    +displayError()
    +displayMainPage()
    +displayConfirm()
    +displayAccountRoles()
    +updatePermission(accountEmail:String)

}
AccountSystem "1"--> "-AccountService 1" AccountService

class VenueSystem {
    +displayVenue(venue: Venue)
    +displayVenues(venues: Venue[*])
    +createVenue(venueDetails: VenueDetails): Boolean
    +viewVenue(name: String): VenueDetails
    +updateVenue(name: String, venueDetails: VenueDetails): Boolean
    +deleteVenue(name: String): Boolean
    +listVenues(): List<Venue>
}
VenueSystem "1"--> "-VenueService 1" VenueService

class EventSystem {
    +createEvent(eventDetails): Boolean
    +viewEvent(name: String): EventDetails
    +deleteEvent(name: String): Boolean
    +updateEvent(eventDetails): Boolean
    +listEvents(): List<Event>
    +listMyEvents(): List<Event>
    +filterEvents(keyWords:String)
    +displayEvents(filterEvents:List<Event>): void
    +displayDate(date: Date): void
    +displayEventDetails(eventDetails): void
    +viewVenueUsage(VenueName: String): List<Event>
    +displayVenueUsage(filterEvents:List<Event>): void
    +viewAvailableVenues(date: Date,time: Time): List<Venue>
}

EventSystem "1"--> "-EventService 1" EventService


class TicketSystem {
    +buyTicket(customerEmail: String, eventName: String, ticketType: String): TicketDetails
    +viewTicketDetails(customerEmail: String, eventName: String): TicketDetails
    +cancelTicket(customerEmail: String, eventName: String): Boolean
    +displayRegistrations(eventName: event):List<Customer>
    +displayTicketDetails(ticketDetails)
    +displayUserTickets(customerEmail: String): List<Ticket>
}
TicketSystem -->"1..TicketService 1"  TicketService

Organiser "1..*" o--> "0..* -organises" Event
Customer "1" o--> "-tickets 0..*" Ticket

@enduml
