@startuml
left to right direction
skinparam monochrome true
skinparam backgroundColor white
skinparam shadowing false
skinparam linetype ortho
skinparam lineThickness 3   ' Thickness of line
skinparam noteMargin 30     ' Margins for comments
skinparam ranksep 100        ' Control vertical spacing
skinparam nodesep 200        ' Control horizontal spacing
skinparam classFontSize 12
skinparam ArrowFontSize 12
skinparam classBorderThickness 1
skinparam classAttributeIconSize 0

hide class circle
hide empty members
hide stereotypes

skinparam class {
    BorderColor black
    ArrowColor black
    FontColor black
    FontName Arial
    FontSize 12
}



' Account Management Group
package "Account Management" {
class ROLE {
        +ADMINISTRATOR
        +ORGANISER
        +CUSTOMER
    }
    class Account {
        - name: String
        - email: String
        - password: String
        - role: ROLE
        +getName(): String
        +getEmail(): String
        +getPassword(): String
        +setName(name: String)
        +setEmail(email: String)
        +setPassword(password: String)
    }
    class Administrator {
    _Administrator(name: String,email:String,password:String)_
    }
    class Organiser {
        - address: String
        - companyName: String
        - phoneNumber: String
        _Organiser(name: String,email:String,password:String,address: String,companyName: String,phoneNumber: String)_
        +getAddress():String
        +getCompanyName():String
        +getPhoneNumber(): String
        +setAddress(address: String)
        +setCompanyName(companyName: String)
        +setPhoneNumber(phoneNumber: String)
    }
    class Customer {
    _Customer(name: String,email:String,password:String)_
    getTickets():Ticket[*]
    }

    class AccountService {
        +createAdminAccount(name: String,email: String,password:String): Boolean
        +createCustomerAccount(name: String,email: String,password:String): Boolean
        +createOrganiserAccount(name: String,email: String,password:String): Boolean
        +registerAccount(name: String,email: String,password:String): Boolean
        +getAccount(email: String): Account
        +getCustomer(customerEmail:String):Customer
        +getOrganiser(organiserEmail:String):Organiser
        +getAccounts():Account[*]
        +deleteAccount(accountEmail: String): Boolean
        +updateAccount(account: Account): Boolean
        +checkAccountExist(accountEmail:String):Boolean
    }


    Administrator --|> Account
    Organiser --|> Account
    Customer --|> Account
    AccountService "1"--> "-accounts * "Account
}

' Venue Management Group
package "Venue Management" {
    class Venue {
        - name: String
        - address: String
        - contactName: String
        - contactPhoneNumber: String
        - contactEmail: String
        - capacity: TicketAvailability[*]
        _Venue(name: String,address: String,contactName: String,contactPhoneNumber: String,contactEmail: String,capacity: TicketAvailability[*])_
        +getName():String
        +getAddress():String
        +getContactName():String
        +getContactPhoneNumber():String
        +getContactEmail():String
        +getTicketAvailabilities():TicketAvailability[*]
        +setName(name: String)
        +setAddress(address: String)
        +setContactName(contactName: String)
        +setContactPhoneNumber(contactPhoneNumber: String)
        +setContactEmail(contactEmail: String)
        +setTicketAvailabilities(ticketAvailabilities:TicketAvailability[*])
    }

    class VenueService {
        +getVenue(venueName: String):Venue
        +getVenues():Venue[*]
        +createVenue(name: String,address: String,contactName: String,contactPhoneNumber: String,contactEmail: String,capacity: TicketAvailability[*]): Boolean
        +updateVenue(name: String,address: String,contactName: String,contactPhoneNumber: String,contactEmail: String,capacity: TicketAvailability[*]): Boolean
        +deleteVenue(venueName: String): Boolean
        +saveVenue(venue:Venue):Boolean
        +checkDuplicateVenue(venue: Venue)
        +getVenueUsage(venueName: String): Event[*]
        +getAvailableVenues(date: Date,time: Time):Venue[*]
    }



    VenueService "1"--> "-venues * "Venue
}

' Event Management Group
package "Event Management" {
    class Event {
        - name: String
        - description: String
        - date: Date
        - time: Time
        - Venue: Venue
        _Event(name: String, description: String, date: Date, time: Time,venue: Venue,ticketQuantities: TicketQuantity)
        +getName(): String
        +getDescription():String
        +getDate():Date
        +getTime():Time
        +getVenue():Venue
        +setName(name: String)
        +setDescription(description: String)
        +setDate(date: Date)
        +setTime(time: Time)
        +setTicketQuantities(ticketQuantities: int)
    }

    class EventService {
        +createEvent(name: String, description: String, date: Date, time: Time, venue: Venue,ticketTypes : String[*], ticketPrices : double[*]): Boolean
        +deleteEvent(name: String): Boolean
        +updateEvent(name: String, description: String, date: Date, time: Time,venue: Venue,ticketTypes : String[*], ticketPrices : double[*]): Boolean
        +getEvent(name: String):Event
        +getEvents():Event[*]
        +saveEvent(event: Event):Boolean

    }



    Venue "1 -venue" <--"*" Event
    EventService "1"--> "-events *" Event
}

' Ticket Management Group
package "Ticket Management" {
    class Ticket {
            - type : String
            - price : Double

        }

    class TicketQuantity {
            - numberSold: int
            - price: double
            _TicketQuantity(ticketTypeName,numberAvailable,price)_
            +getNumberRemain():int
            +getNumberSold():int
            +getPrice():double
            +setNumberRemain(numberRemain: int)
            +setNumberSold(numberSold: int)
            +setPrice(price: double)
        }
     class TicketAvailability {
                - ticketTypeName: String
                - numberAvailable: int
                _TicketAvailability(ticketTypeName,numberAvailable)_
                +getTicketTypeName():String
                +getNumberAvailable():int
                +setTicketTypeName(ticketTypeName: String)
                +setNumberAvailable(number: int)

            }

    class TicketService {
        +getTicket(customerEmail: String, eventName: String): Ticket
        +getMyTicket(customerEmail: String):Ticket[*]
        +buyTicket(customerEmail: String, eventName: String, ticketQuantity: String): Ticket
        +getCustomerRegistrations(eventName: event):Customer[*]
        +getTicketOwner(eventName: String):Customer
        +getTicketEvent(customerEmail: String):Event
        +getTicketQuantity(eventName: String,customerEmail: String):TicketQuantity
    }


    Venue "1 -venue" --> "-ticketAvailabilities *" TicketAvailability : creates
    TicketAvailability --|> TicketQuantity
    Event "1"--> "-TicketQuantities *" TicketQuantity: determines price
    Customer "1"--> "-tickets 0..* " Ticket : purchases
    Ticket "1"--> "-event 1" Event : related to
    Ticket "1"--> "1 -ticketQuantity" TicketQuantity : get Info
    TicketService "1"-->"-tickets *" Ticket
}

' System classes for each module
class AccountSystem {
    +login(email: String, password: String): Boolean
    +logout(): void
    +createAccount(accountDetails): Boolean
    +deleteAccount(accountEmail: String): Boolean
    +selectAccount(accountEmail:String)
    +viewAccount(accountEmail: String): AccountDetails
    +updateAdministratorAccount(newName: String, newPassword:String,newEmail:String)
    +updateCustomerAccount(newName: String, newPassword:String,newEmail:String)
    +updateOrganizerAccount(newName: String, newPassword:String,newEmail:String,newAddress:String,newCompanyName :String, newPhoneNumber:String)
    +displayMainPage()
    +displayEditAccountPage(selectedAccount)
    +displayAccountsPage(accounts:Account[*])
    +disableAccount(accountEmail:String)
    +displayEditAccountPage(accountEmail: String)
    +displayError()
    +displayConfirm()
    +displayAccountRoles()
    +updatePermission(accountEmail:String)

}
AccountSystem "1"--> "-AccountService 1" AccountService

class VenueSystem {
    +displayVenuePage(venue: Venue)
    +displayVenuesPage(venues: Venue[*])
    +createVenue(venueDetails)
    +viewVenue(name: String)
    +updateVenue(venueDetails)
    +deleteVenue(name: String)
    +listVenues()
    +listAvailableVenues(date: Date,time: Time)
    +listVenueUsage(venueName: String)
    +displayAvailableVenuesPage(availableVenues:Venue[*])
    +displayVenueUsagePage(pastEvents:Event[*])
}
VenueSystem "1"--> "-VenueService 1" VenueService

class EventSystem {
    +createEvent(eventDetails)
    +viewEvent(name: String)
    +deleteEvent(name: String)
    +updateEvent(eventDetails)
    +listEvents()
    +listMyEvents(customerEmail: String)
    +searchEvents(keyWords:String)
    +displayListEventsPage(Events:Event[*])
    +displayDatePage(date: Date)
    +displayEventDetailsPage(eventDetails)
    +showCreateEventPage()
    +displayViewEventPage(Event: event)
    +showUpdateEvent(name: String)
    +displayUpdateEventPage(Event: event)
}

EventSystem "1"--> "-EventService 1" EventService


class TicketSystem {
    +listMyTickets(customerEmail: String)
    +listTicketDetails(ticket:Ticket)
    +listRegisteredCustomer(eventName: String)
    +buyTicket(customerEmail: String, eventName: String, ticketType: String)
    +viewTicketDetails(customerEmail: String, eventName: String)
    +cancelTicket(customerEmail: String, eventName: String)
    +displayRegistrationsPage(registeredCus:Customer[*])
    +displayTicketDetailsPage(ticketDetails)
    +displayMyTicketsPage(Ticket[*])
}
TicketSystem -->"1..TicketService 1"  TicketService

Organiser "1..*" o--> "0..* -organises" Event
Customer "1" o--> "-tickets 0..*" Ticket

@enduml
