@startuml
!define PLANTUML_LIMIT_SIZE 8192
top to bottom direction

skinparam layout neato
skinparam shadowing false
skinparam linetype ortho
skinparam lineThickness 3   ' Thickness of line
skinparam noteMargin 30     ' Margins for comments
skinparam ranksep 100       ' Control vertical spacing
skinparam nodesep 200       ' Control horizontal spacing
skinparam classFontSize 12
skinparam ArrowFontSize 12
skinparam classBorderThickness 1
skinparam classAttributeIconSize 12
skinparam ClassFontColor #00008B

hide class circle
hide empty members


skinparam class {
    BorderColor black
    ArrowColor black
    FontColor black
    FontName Arial
    FontSize 12
    classAttributeIconSize 20
}

package "repositories" #LightYellow {
    class CustomerRepository {
        +findById(id: Long): Account
        +findByEmail(email: Long): Account
        +findAll(): Account[*]
        +save(customer: Customer): Boolean
        +delete(customer: Customer): Boolean
        +deleteByEmail(email: Long): Boolean
    }
    class OrganiserRepository {
        +findById(id: Long): Account
        +findByEmail(email: Long): Account
        +findAll(): Account[*]
        +save(organiser: Organiser): Boolean
        +delete(organiser: Organiser): Boolean
        +deleteByEmail(email: Long): Boolean
    }
    class AdministratorRepository {
        +findById(id: Long): Account
        +findByEmail(email: Long): Account
        +findAll(): Account[*]
        +save(administrator: Administrator): Boolean
        +delete(administrator: Administrator): Boolean
        +deleteByEmail(email: Long): Boolean
    }
    class VenueRepository {
        +findById(id: Long): Venue
        +findAllByDateTime(date: Date,time: Time) Venue[*]
        +findAll(): Venue[*]
        +save(venue: Venue): Boolean
        +delete(venue: Venue): Boolean
    }

    class EventRepository {
        +findById(id: Long): Event
        +findAllByEmail(email: Long): Event[*]
        +findAll(): Event[*]
        +save(event: Event): Boolean
        +delete(event: Event): Boolean
    }

    class TicketRepository {
        +findById(id: Long): Ticket
        +findAllByEmail(email: Long): Ticket[*]
        +findAll(): Ticket[*]
        +save(ticket: Ticket): Boolean
        +delete(ticket: Ticket): Boolean
        +findCustomerByEvent(eventName: String): Customer[*]
        +CountByEvent(eventName: String, contactEmail: String): TicketQuantity
    }

}


' Event Management Group
package "services" #LightYellow {
    class AccountService {
        {static}+AccountService(CustomerRepository,OrganiserRepository,AdministratorRepository)
         +createAdminAccount(name: String,email: String,password:String): Boolean
         +createCustomerAccount(name: String,email: String,password:String): Boolean
         +createOrganiserAccount(name: String,email: String,password:String): Boolean
         +registerAccount(name: String,email: String,password:String): Boolean
         +getAccount(email: String): Account
         +getCustomer(customerEmail:String):Customer
         +getOrganiser(organiserEmail:String):Organiser
         +getAccounts():Account[*]
         +deleteAccount(accountEmail: String): Boolean
         +updateAccount(account: Account): Boolean
         +checkAccountExist(accountEmail:String):Boolean
      }

    class VenueService {
        {static}+VenueService(VenueRepository,TicketRepository,OrganiserRepository)
        +getVenue(venueName: String):Venue
        +getVenues():Venue[*]
        +createVenue(name: String,address: String,contactName: String,contactPhoneNumber: String,contactEmail: String,capacity: TicketAvailability[*]): Boolean
        +updateVenue(name: String,address: String,contactName: String,contactPhoneNumber: String,contactEmail: String,capacity: TicketAvailability[*]): Boolean
        +deleteVenue(venueName: String): Boolean
        +saveVenue(venue:Venue):Boolean
        +checkDuplicateVenue(venue: Venue)
        +getVenueUsage(venueName: String): Event[*]
        +getAvailableVenues(date: Date,time: Time):Venue[*]
    }

    class EventService {
        {static}+EventService(EventRepository,TicketRepository
        +createEvent(name: String, description: String, date: Date, time: Time, venue: Venue,ticketTypes : String[*], ticketPrices : double[*]): Boolean
        +deleteEvent(name: String): Boolean
        +updateEvent(name: String, description: String, date: Date, time: Time,venue: Venue,ticketTypes : String[*], ticketPrices : double[*]): Boolean
        +getEvent(name: String):Event
        +getEventDetails(name: String):
        +saveEvent(event: Event):Boolean
    }

   class TicketService {
        {static}+TicketService(TicketRepository,CustomerRepository,EventRepository)
        +getTicket(customerEmail: String, eventName: String): Ticket
        +getMyTicket(customerEmail: String):Ticket[*]
        +buyTicket(customerEmail: String, eventName: String, ticketQuantity: String): Ticket
        +getCustomerRegistrations(eventName: event):Customer[*]
        +getTicketOwner(eventName: String):Customer
        +getTicketEvent(customerEmail: String):Event
        +getTicketQuantity(eventName: String,customerEmail: String):TicketQuantity
    }


}

' Ticket Management Group
package "models" #LightYellow {
  interface IAccount {
        + getName(): String
        + getEmail(): String
        + getPassword(): String
    }
class ROLE {
        +ADMINISTRATOR
        +ORGANISER
        +CUSTOMER
    }
    class Account {
        - id: Long
        - name: String
        - email: String
        - password: String
        - role: ROLE
        +getId():Long
        +getName(): String
        +getEmail(): String
        +getPassword(): String
        +setName(name: String)
        +setEmail(email: String)
        +setPassword(password: String)
    }
    class Administrator {
     {static}Administrator()
    {static}Administrator(name: String,email:String,password:String)_
    }
    class Organiser {
        - address: String
        - companyName: String
        - phoneNumber: String
        {static}Organiser()
        {static}Organiser(name: String,email:String,password:String,address: String,companyName: String,phoneNumber: String)_
        +getAddress():String
        +getCompanyName():String
        +getPhoneNumber(): String
        +setAddress(address: String)
        +setCompanyName(companyName: String)
        +setPhoneNumber(phoneNumber: String)
    }
    class Customer {
    {static}Customer()
    {static}Customer(name: String,email:String,password:String)_
    getTickets():Ticket[*]
    }


      Administrator --|> Account
      Organiser --|> Account
      Customer --|> Account
      Organiser "1..*" o--> "0..* -organises" Event
      Customer "1" o--> "-tickets 0..*" Ticket


      class Venue {
        - id: Long
        - name: String
        - address: String
        - contactName: String
        - contactPhoneNumber: String
        - contactEmail: String
        - capacity: TicketAvailability[*]
        {static}Venue()
        {static}Venue(name: String,address: String,contactName: String,contactPhoneNumber: String,contactEmail: String,capacity: TicketAvailability[*])_
        +getName():String
        +getAddress():String
        +getContactName():String
        +getContactPhoneNumber():String
        +getContactEmail():String
        +getTicketAvailabilities():TicketAvailability[*]
        +setName(name: String)
        +setAddress(address: String)
        +setContactName(contactName: String)
        +setContactPhoneNumber(contactPhoneNumber: String)
        +setContactEmail(contactEmail: String)
        +setTicketAvailabilities(ticketAvailabilities:TicketAvailability[*])
    }


    Venue "1 -venue" <--"*" Event
 class Event {
        - id: Long
        - name: String
        - description: String
        - date: Date
        - time: Time
        - Venue: Venue
       {static}Event()
       {static}Event(name: String, description: String, date: Date, time: Time,venue: Venue,ticketQuantities: TicketQuantity)
        +getName(): String
        +getDescription():String
        +getDate():Date
        +getTime():Time
        +getVenue():Venue
        +setName(name: String)
        +setDescription(description: String)
        +setDate(date: Date)
        +setTime(time: Time)
        +setTicketQuantities(ticketQuantities: int)
    }

    class Ticket {
            - id: Long
            - type : String
            - price : Double
            {static}Ticket()
            {static}Ticket(type: String, price: Double)
            +getId():Long
        }

    class TicketQuantity {
            - id: Long
            - numberSold: int
            - price: double
            {static}TicketQuantity()
            {static}TicketQuantity(ticketTypeName,numberAvailable,price)
            +getId():Long
            +getNumberRemain():int
            +getNumberSold():int
            +getPrice():double
            +setNumberRemain(numberRemain: int)
            +setNumberSold(numberSold: int)
            +setPrice(price: double)
        }
     class TicketAvailability {
                - id: Long
                - ticketTypeName: String
                - numberAvailable: int
                {static}TicketAvailability()
                {static}TicketAvailability(ticketTypeName,numberAvailable)
                +getId():Long
                +getTicketTypeName():String
                +getNumberAvailable():int
                +setTicketTypeName(ticketTypeName: String)
                +setNumberAvailable(number: int)

            }




    Venue "1 -venue" --> "-ticketAvailabilities *" TicketAvailability : creates
    TicketAvailability --|> TicketQuantity
    Event "1"--> "-TicketQuantities *" TicketQuantity: determines price
    Customer "1"--> "-tickets 0..* " Ticket : purchases
    Ticket "1"--> "-event 1" Event : related to
    Ticket "1"--> "1 -ticketQuantity" TicketQuantity : get Info
    TicketService "1"-->"-tickets *" Ticket
}

package "controllers" #LightYellow{

package "DTOs" #LightYellow {

   class ErrorType <<Enumeration>> {
    OVERBOOKED_RESERVATION
    OVERBOOKED_WALK_IN
    DOUBLE_BOOKED_RESERVATION
    DOUBLE_BOOKED_WALK_IN
    OVERBOOKED_ALTERATION
    DOUBLE_BOOKED_ALTERATION
    }
    class ErrorMessageDTO {
        +type: ErrorType
        +message: String
        {static}ErrorDetails()
        {static}ErrorDetails(type: ErrorType, message: String)
        getMessage():String
        getType(): ErrorType

    }

    class AccountDTO {
        +name: String
        +email: String
        +role: ROLE
    }

    class VenueDTO {
        +name: String
        +address: String
        +capacity: TicketAvailability[*]
    }

    class EventDTO {
        +name: String
        +description: String
        +date: Date
        +time: Time
        +venue: VenueDTO
    }

    class TicketDTO {
        +type: String
        +price: Double
    }

}
' System classes for each module
class AccountSystem {
    +login(email: String, password: String): Boolean
    +logout(): void
    +createAccount(accountDetails): Boolean
    +deleteAccount(accountEmail: String): Boolean
    +selectAccount(accountEmail:String)
    +viewAccount(accountEmail: String): AccountDetails
    +updateAdministratorAccount(newName: String, newPassword:String,newEmail:String)
    +updateCustomerAccount(newName: String, newPassword:String,newEmail:String)
    +updateOrganizerAccount(newName: String, newPassword:String,newEmail:String,newAddress:String,newCompanyName :String, newPhoneNumber:String)
    +updatePermission(accountEmail:String)

}
AccountSystem "1"--> "-AccountService 1" AccountService

class VenueSystem {
    +createVenue(venueDetails)
    +viewVenue(name: String)
    +updateVenue(venueDetails)
    +deleteVenue(name: String)
    +listVenues()
    +listAvailableVenues(date: Date,time: Time)
    +listVenueUsage(venueName: String)
}
VenueSystem "1"--> "-VenueService 1" VenueService

class EventSystem {
    +createEvent(eventDetails)
    +viewEvent(name: String)
    +deleteEvent(name: String)
    +updateEvent(eventDetails)
    +listEvents()
    +listMyEvents(customerEmail: String)
    +searchEvents(keyWords:String)
    +showCreateEventPage()
    +showUpdateEvent(name: String)
}

EventSystem "1"--> "-EventService 1" EventService


class TicketSystem {
    +listMyTickets(customerEmail: String)
    +listTicketDetails(ticket:Ticket)
    +listRegisteredCustomer(eventName: String)
    +buyTicket(customerEmail: String, eventName: String, ticketType: String)
    +viewTicketDetails(customerEmail: String, eventName: String)
    +cancelTicket(customerEmail: String, eventName: String)
}
TicketSystem -->"1..TicketService 1"  TicketService

ErrorMessageDTO ..> ErrorType : <<use>>
' Connect DTOs with Systems using dashed lines for dependency
AccountSystem ..> AccountDTO
VenueSystem ..> VenueDTO
EventSystem ..> EventDTO
TicketSystem ..> TicketDTO
       AccountSystem ..> ErrorMessageDTO
        VenueSystem ..> ErrorMessageDTO
        EventSystem ..> ErrorMessageDTO
        TicketSystem ..> ErrorMessageDTO
}
    EventService "1"--> "-events *" EventRepository
    AccountService "1"--> "-accounts * "CustomerRepository
    AccountService "1"--> "-accounts * "OrganiserRepository
    AccountService "1"--> "-accounts * "AdministratorRepository
    VenueService "1"--> "-venues * "VenueRepository

   ' Connect Repositories with Models
    CustomerRepository ..> models.Account : <<import>>
    OrganiserRepository ..> models.Account : <<import>>
    AdministratorRepository ..> models.Account : <<import>>
    VenueRepository ..> models.Venue : <<import>>
    EventRepository ..> models.Event : <<import>>
    TicketRepository ..> models.Ticket : <<import>>




@enduml
