@startuml
left to right direction
skinparam monochrome true
skinparam backgroundColor white
skinparam shadowing false
skinparam linetype ortho
skinparam lineThickness 3   ' Thickness of line
skinparam noteMargin 30     ' Margins for comments
skinparam ranksep 100        ' Control vertical spacing
skinparam nodesep 200        ' Control horizontal spacing
skinparam classFontSize 12
skinparam ArrowFontSize 12
skinparam classBorderThickness 1
skinparam classAttributeIconSize 0

hide class circle
hide empty members
hide stereotypes

skinparam class {
    BorderColor black
    ArrowColor black
    FontColor black
    FontName Arial
    FontSize 12
}

' Account Management Group
package "Account Management" {
    class Account {
        - name: String
        - email: String
        - password: String
    }
    class Administrator {
    }
    class Organiser {
        - address: String
        - companyName: String
        - phoneNumber: String
    }
    class User {
    }

    class AccountService {
        +getAccount(email: String, password: String): Boolean
        +createAccount(accountDetails: AccountDetails): Boolean
        +deleteAccount(accountId: String): Boolean
        +readAccount(accountId: String): AccountDetails
        +updateAccount(accountId: String, accountDetails: AccountDetails): Boolean

    }

    class AccountCreationRequest {
        - accountDetails: AccountDetails
    }

    Administrator --|> Account
    Organiser --|> Account
    User --|> Account
    AccountService --> Account
}

' Venue Management Group
package "Venue Management" {
    class Venue {
        - name: String
        - address: String
        - contactName: String
        - contactPhoneNumber: String
        - contactEmail: String
        - capacity: int
    }

    class VenueService {
        +getVenue(venue: Venue):Venue
        +getVenues():Venue[*]
        +createVenue(venueDetails: VenueDetails): Boolean
        +readVenue(name: String): VenueDetails
        +updateVenue(name: String, venueDetails: VenueDetails): Boolean
        +deleteVenue(name: String): Boolean
        +getVenue(name: String): Venue
        +saveVenue(name: String):Boolean
    }

    class VenueCreationRequest {
        - venueDetails: VenueDetails
    }

    VenueService --> Venue
}

' Event Management Group
package "Event Management" {
    class Event {
        - name: String
        - description: String
        - date: Date
        - time: Time
    }

    class EventService {
        +readEvent(name: String): EventDetails
        +deleteEvent(name: String): Boolean
        +updateEvent(name: String, eventDetails: EventDetails): Boolean
        +getEvent(name: String):Event
        +getEventName(name: String)):String
        +getTicketTypes(venue: Venue): (TicketType,number)
        +createEvent(details): Boolean
        +getVenue(venue: Venue): venueDetails
        +getEvents():List<Event>
        +saveEvent(eventId: String):Boolean
    }

    class EventCreationRequest {
        - eventDetails: EventDetails
    }

    Venue "1 -venue" <-- Event
    EventService --> Event
}

' Ticket Management Group
package "Ticket Management" {
    class Ticket {
            ' Ticket class with no attributes, representing a relationship
        }

    class TicketInfo {
            - name: String
            - numberAvailable: int
            - numberSold: int
            - price: double
        }

    class TicketService {
        +getTicket(userEmail: String, eventId: String, ticketType: String): TicketDetails
        +readTicket(userEmail: String, eventId: String): TicketDetails
    }


    class TicketPurchaseRequest {
        - ticketDetails: TicketDetails
    }

    Venue "1 -venue" --> TicketType : creates
        Event --> "1 -ticketType" TicketType : determines price
        User --> "0..* -tickets" Ticket : purchases
        Ticket --> "1 -event" Event : related to
        Ticket --> "1 -ticketType" TicketType : is of type
        TicketService --> Ticket
}

' System classes for each module
class AccountSystem {
    +login(email: String, password: String): Boolean
    +logout(): void
    +createAccount(accountDetails: AccountDetails): Boolean
    +deleteAccount(accountId: String): Boolean
    +viewAccount(accountId: String): AccountDetails
    +updateAccount(accountId: String, accountDetails: AccountDetails): Boolean
}
AccountSystem --> AccountService

class VenueSystem {
    +displayVenue(venue: Venue)
    +displayVenues(venues: Venue[*])
    +createVenue(venueDetails: VenueDetails): Boolean
    +viewVenue(name: String): VenueDetails
    +updateVenue(name: String, venueDetails: VenueDetails): Boolean
    +deleteVenue(name: String): Boolean
    +listVenues(): List<Venues>
}
VenueSystem --> VenueService

class EventSystem {
    +createEvent(eventDetails: EventDetails): Boolean
    +viewEvent(name: String): EventDetails
    +deleteEvent(name: String): Boolean
    +updateEvent(name: String, eventDetails: EventDetails): Boolean
    +listEvents(): List<Events>
    +listMyEvents(): List<Events>
}
EventSystem --> EventService

class TicketSystem {
    +buyTicket(userEmail: String, eventId: String, ticketType: String): TicketDetails
    +viewTicket(ticketId: String): TicketDetails
    +listUserTickets(userEmail: String): List<Tickets>
    +cancelTicket(ticketId: String): Boolean
}
TicketSystem --> TicketService

Organiser "1..*" o--> "0..* -organises" Event
User "1" o--> "-tickets 0..*" Ticket

@enduml
