@startuml
left to right direction
skinparam monochrome true
skinparam backgroundColor white
skinparam shadowing false
skinparam linetype ortho
skinparam lineThickness 3   ' Thickness of line
skinparam noteMargin 30     ' Margins for comments
skinparam ranksep 100        ' Control vertical spacing
skinparam nodesep 200        ' Control horizontal spacing
skinparam classFontSize 12
skinparam ArrowFontSize 12
skinparam classBorderThickness 1
skinparam classAttributeIconSize 0

hide class circle
hide empty members
hide stereotypes

skinparam class {
    BorderColor black
    ArrowColor black
    FontColor black
    FontName Arial
    FontSize 12
}

' Account Management Group
package "Account Management" {
    class Account {
        - name: String
        - email: String
        - password: String
        +getName(): String
        +getEmail(): String
        +getPassword(): String
        +setName(name: String)
        +setPassword(password: String)
    }
    class Administrator {
    }
    class Organiser {
        - address: String
        - companyName: String
        - phoneNumber: String
        +getAddress():String
        +getCompanyName():String
        +getPhoneNumber(): String
        +setAddress(address: String)
        +setCompanyName(companyName: String)
        +setPhoneNumber(phoneNumber: String)
    }
    class User {
    }

    class AccountService {
        +getAccount(email: String): Boolean
        +createAccount(accountDetails: AccountDetails): Boolean
        +deleteAccount(accountEmail: String): Boolean
        +readAccount(accountEmail: String): AccountDetails
        +updateAccount(accountEmail: String, accountDetails: AccountDetails): Boolean
        +getAccounts():Account[*]
        +checkAccountExist(accountEmail:String):Boolean
    }

    class AccountCreationRequest {
        - accountDetails: AccountDetails
    }

    Administrator --|> Account
    Organiser --|> Account
    User --|> Account
    AccountService --> Account
}

' Venue Management Group
package "Venue Management" {
    class Venue {
        - name: String
        - address: String
        - contactName: String
        - contactPhoneNumber: String
        - contactEmail: String
        +getName():String
        +getAddress():String
        +getContactName():String
        +getContactPhoneNumber():String
        +getContactEmail():String
        +setAddress(address: String)
        +setContactName(contactName: String)
        +setContactPhoneNumber(contactPhoneNumber: String)
        +setContactEmail(contactEmail: String)
    }

    class VenueService {
        +getVenue(venue: Venue):Venue
        +getVenues():Venue[*]
        +createVenue(venueDetails: VenueDetails): Boolean
        +readVenue(name: String): VenueDetails
        +updateVenue(name: String, venueDetails: VenueDetails): Boolean
        +deleteVenue(name: String): Boolean
        +getVenue(name: String): Venue
        +getVenueName(name: String)):String
        +getVenueAddress(name: String):String
        +getVenueContactName(name: String):String
        +getVenueContactPhoneNumber(name: String): String
        +getVenueContactEmail(name: String):String
        +getVenueCapacity(name: String): int
        +saveVenue(name: String):Boolean
        +checkDuplicateVenue(venue: Venue)
    }

    class VenueCreationRequest {
        - venueDetails: VenueDetails
    }

    VenueService --> Venue
}

' Event Management Group
package "Event Management" {
    class Event {
        - name: String
        - description: String
        - date: Date
        - time: Time
        +getName(): String
        +getDescription():String
        +getDate():Date
        +getTime():Time
        +setDescription(description: String)
        +setDate(date: Date)
        +setTime(time: Time)
    }

    class EventService {
        +createEvent(eventDetails: EventDetails): Boolean
        +readEvent(name: String): EventDetails
        +deleteEvent(name: String): Boolean
        +updateEvent(name: String, eventDetails: EventDetails): Boolean
        +getEvent(name: String):Event
        +getEventName(name: String)):String
        +getEventDescription(name: String):String
        +getEventDate(name: String):Date
        +getEventTime(name: String):Time
        +getEvents():List<Event>
        +saveEvent(eventId: String):Boolean
        +getVenueUsage(venueName: String): List<Events>
    }

    class EventCreationRequest {
        - eventDetails: EventDetails
    }

    Venue "1 -venue" <-- Event
    EventService --> Event
}

' Ticket Management Group
package "Ticket Management" {
    class Ticket {
            ' Ticket class with no attributes, representing a relationship
        +getUser(eventName: String):User
        +getEvent(userEmail: String):Event
        +getTicketInfo(eventName: String,userEmail: String):TicketInfo
        }

    class TicketInfo {
            - numberAvailable: int
            - numberSold: int
            - price: double
            +getNumberAvailable():int
            +getNumberSold():int
            +getPrice():double
            +setNumberAvailable(numberAvailable: int)
            +setNumberSold(numberSold: int)
            +setPrice(price: double)
        }
     class TicketType {
                - ticketTypeName: String
                - number: int
                +getTicketTypeName():String
                +getNumber():int
                +setTicketTypeName(ticketTypeName: String)
                +setNumber(number: int)

            }

    class TicketService {
        +getTicket(userEmail: String, eventName: String): TicketDetails
         +buyTicket(userEmail: String, eventName: String, ticketType: String): TicketDetails
        +getRegistrations(eventName: event):List<User>

    }


    class TicketPurchaseRequest {
        - ticketDetails: TicketDetails
    }

    Venue "1 -venue" --> "1..*"TicketType : creates
    TicketType "1"-->"1 Info" TicketInfo : combines

    Event --> "1 -ticketInfo" TicketInfo: determines price
    User --> "0..* -tickets" Ticket : purchases
    Ticket --> "1 -event" Event : related to
    Ticket --> "1 -ticketInfo" TicketInfo : get Info
    TicketService --> Ticket
}

' System classes for each module
class AccountSystem {
    +login(email: String, password: String): Boolean
    +logout(): void
    +createAccount(accountDetails: AccountDetails): Boolean
    +deleteAccount(accountEmail: String): Boolean
    +viewAccount(accountEmail: String): AccountDetails
    +updateAdministratorAccount(newName: String, newPassword:String)
    +updateUserAccount(newName: String, newPassword:String)
    +updateOrganizerAccount(newName: String, newPassword:String,newAddress:String,newCompanyName :String, newPhoneNumber:String)
    +displayEditAccountPage(selectedAccount)
    +displayAccounts(accounts:Account[*])
    +updateDisplay()
    +disableAccount(accountEmail:String):Boolean
    +selectAccount(accountEmail:String)
    +updatePermission(accountEmail:String)
    +showEditAccount(email: String)
    +showError()
    +showMainPage()
    +confirm()

}
AccountSystem --> AccountService

class VenueSystem {
    +displayVenue(venue: Venue)
    +displayVenues(venues: Venue[*])
    +createVenue(venueDetails: VenueDetails): Boolean
    +viewVenue(name: String): VenueDetails
    +updateVenue(name: String, venueDetails: VenueDetails): Boolean
    +deleteVenue(name: String): Boolean
    +listVenues(): List<Venues>
}
VenueSystem --> VenueService

class EventSystem {
    +createEvent(eventDetails: EventDetails): Boolean
    +viewEvent(name: String): EventDetails
    +deleteEvent(name: String): Boolean
    +updateEvent(name: String, eventDetails: EventDetails): Boolean
    +listEvents(): List<Event>
    +listMyEvents(): List<Event>
    +filterEvents(keyWords:String)
    +displayEvents(filterEvents:List<Event>): void
    +DisplayDate(date: Date): void
    +displayEventDetails(eventDetails: EventDetails): void
    +getVenueUsage(VenueName: String): List<Event>
    +displayVenueUsage(filterEvents:List<Event>): void
}
EventSystem --> EventService

class TicketSystem {
    +buyTicket(userEmail: String, eventName: String, ticketType: String): TicketDetails
    +viewTicketDetails(userEmail: String, eventName: String): TicketDetails
    +listUserTickets(userEmail: String): List<Tickets>
    +cancelTicket(userEmail: String, eventName: String): Boolean
    +getRegistrations(eventName: event):List<User>
    +displayRegistrations(eventName: event):List<User>
    +displayTicketDetails(ticketDetails)
}
TicketSystem --> TicketService

Organiser "1..*" o--> "0..* -organises" Event
User "1" o--> "-tickets 0..*" Ticket

@enduml
