package org.work1.eventmanagement.controller;

public enum ErrorType {
    NONE, OVERBOOKED_RESERVATION, OVERBOOKED_WALK_IN, DOUBLE_BOOKED_RESERVATION, DOUBLE_BOOKED_WALK_IN, OVERBOOKED_ALTERATION, DOUBLE_BOOKED_ALTERATION
}
